SNOW-2176180: install with uv instead of pipx

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -39,14 +39,26 @@ runs:
       shell: bash
       run: echo "SF_GITHUB_ACTION=true" >> "$GITHUB_ENV"
 
-    - name: >
-        Download snowflake-cli
-        ${{ inputs.custom-github-ref && format('from git ref {0}', inputs.custom-github-ref) || (inputs.cli-version && format('version {0}', inputs.cli-version) || 'latest version') }}
+    - uses: astral-sh/setup-uv@v6
+      with:
+        python-version: "3.12"
+
+    - name: Either cli-version or custom-github-ref allowed
+      if: ${{ inputs.cli-version != '' && inputs.custom-github-ref != '' }}
       shell: bash
-      run: bash $GITHUB_ACTION_PATH/scripts/install-snowcli.sh
-      env:
-        CLI_VERSION: ${{ inputs.cli-version }}
-        CUSTOM_GITHUB_REF: ${{ inputs.custom-github-ref }}
+      run: |
+        echo "You cannot set BOTH cli-version and custom-github-ref"
+        exit 1
+
+    - name: Install snowflake-cli (specific version)
+      if: ${{ inputs.cli-version != '' && inputs.custom-github-ref == '' }}
+      shell: bash
+      run: uv tool install snowflake-cli==${{ inputs.cli-version }}
+
+    - name: Install snowflake-cli (custom ref)
+      if: ${{ inputs.cli-version == '' && inupts.custom-github-ref != '' }}
+      shell: bash
+      run: uv tool install "git+https://github.com/snowflakedb/snowflake-cli.git@${{ inputs.custom-github-ref }}"
 
     - name: Set up config.toml
       shell: bash
